# CHEM7370 Class 16
## Calculating bond lengths and angles
Let's now go back to the XYZ geometry of toluene. We want to find the bond lengths present in this molecule.

At the moment, the nuclear coordinates are contained in the string variable `xyz`, so first we need to convert them into a NumPy array.

In [1]:
import numpy as np
xyz = '''15
XYZ geometry from RDKit
C 2.2126 -0.1714 0.0957
C 0.7202 -0.0520 0.0066
C 0.0966 1.1905 0.1749
C -1.2944 1.2963 0.1233
C -2.0737 0.1601 -0.0865
C -1.4630 -1.0830 -0.2404
C -0.0721 -1.1901 -0.1890
H 2.5123 -0.3511 1.1327
H 2.6995 0.7425 -0.2605
H 2.5763 -0.9961 -0.5262
H 0.6916 2.0845 0.3467
H -1.7697 2.2653 0.2497
H -3.1565 0.2429 -0.1257
H -2.0699 -1.9706 -0.3979
H 0.3903 -2.1678 -0.3034
'''
xyz_lines = xyz.split("\n")
natoms = int(xyz_lines[0])
lcoord = []
atom_symbols = []
for atom in xyz_lines[2:natoms+2]:
    atom_symbols.append(atom.split()[0])
    lcoord.append([float(x) for x in atom.split()[1:]])
lcoord = np.array(lcoord)
print(lcoord)

[[ 2.2126 -0.1714  0.0957]
 [ 0.7202 -0.052   0.0066]
 [ 0.0966  1.1905  0.1749]
 [-1.2944  1.2963  0.1233]
 [-2.0737  0.1601 -0.0865]
 [-1.463  -1.083  -0.2404]
 [-0.0721 -1.1901 -0.189 ]
 [ 2.5123 -0.3511  1.1327]
 [ 2.6995  0.7425 -0.2605]
 [ 2.5763 -0.9961 -0.5262]
 [ 0.6916  2.0845  0.3467]
 [-1.7697  2.2653  0.2497]
 [-3.1565  0.2429 -0.1257]
 [-2.0699 -1.9706 -0.3979]
 [ 0.3903 -2.1678 -0.3034]]


We will need a function that takes two `numpy` arrays `atom1` and `atom2` (each with 3 coordinates) and calculates the distance between the two atoms. Complete this function.

In [2]:
def distance(atom1,atom2):
#    return np.sqrt((atom2[0]-atom1[0])*(atom2[0]-atom1[0])+(atom2[1]-atom1[1])*(atom2[1]-atom1[1])+(
#        atom2[2]-atom1[2])*(atom2[2]-atom1[2]))
    return np.sqrt(np.sum((atom2-atom1)*(atom2-atom1)))

Let's now pick every pair of atoms (with the double `for` loop), calculate the distance, and print it if it's less than 1.6 Angstroms (so that it likely represents a bond). Complete the code inside the loops.

In [4]:
for i in range(natoms):
    for j in range(i):
        dist = distance(lcoord[i,:],lcoord[j,:])
        if dist < 1.6:
            print(dist)

1.4998176322473344
1.400359989431289
1.3959717762189894
1.3936552550756591
1.3935341079428232
1.4004535908054931
1.3959638892177693
1.0942948323006922
1.0950631306002407
1.0950650163346467
1.0875551664168581
1.0866683256633551
1.0866684498962873
1.0867233410578794
1.0875653589554977


Modify the code above so that, for every bond, it also prints the bond type (C-C or C-H). Remember that we saved the `atom_symbols` array.

In [5]:
for i in range(natoms):
    for j in range(i):
        dist = distance(lcoord[i,:],lcoord[j,:])
        if dist < 1.6:
            print(atom_symbols[i]+"-"+atom_symbols[j],dist)

C-C 1.4998176322473344
C-C 1.400359989431289
C-C 1.3959717762189894
C-C 1.3936552550756591
C-C 1.3935341079428232
C-C 1.4004535908054931
C-C 1.3959638892177693
H-C 1.0942948323006922
H-C 1.0950631306002407
H-C 1.0950650163346467
H-C 1.0875551664168581
H-C 1.0866683256633551
H-C 1.0866684498962873
H-C 1.0867233410578794
H-C 1.0875653589554977


As our last task, let's find the bond angles in this molecule.

A short refresher from geometry: the dot product `np.dot(v1,v2)` of two vectors *v<sub>1</sub>=(x<sub>1</sub>,y<sub>1</sub>,z<sub>1</sub>)* and *v<sub>2</sub>=(x<sub>2</sub>,y<sub>2</sub>,z<sub>2</sub>)* equals *x<sub>1</sub>x<sub>2</sub>+y<sub>1</sub>y<sub>2</sub>+z<sub>1</sub>z<sub>2</sub>*. This dot product is equal to the product of the lengths of *v<sub>1</sub>* and *v<sub>2</sub>* times the cosine of the angle between the two vectors. If you calculate the cosine, you can use the inverse cosine function `np.arccos()` to get the angle - just remember that this angle will be in radians, and you need to multiply it by `180.0/np.pi` to convert it to degrees.

Complete the function that takes three `numpy` arrays `atom1`, `atom2`, `atom3` (each with 3 coordinates) and calculates the `atom1-atom2-atom3` angle.

In [6]:
def angle(atom1,atom2,atom3):
    v1 = atom1 - atom2
    v2 = atom3 - atom2
    v1dotv2 = np.dot(v1,v2)
    lenv1 = distance(atom2,atom1)
    lenv2 = distance(atom3,atom2)
    cosalpha = v1dotv2/(lenv1*lenv2)
    return np.arccos(cosalpha)*180.0/np.pi

Now, use the definition of `angle` to print the angles between any two bonds sharing a common atom. Remember that for any three atoms `atom1`, `atom2`, `atom3` you need to check three possibilities - each of the three atoms can be bonded to the other two. For example, if `atom1` is bonded to both `atom2` and `atom3`, you need to print the angle `atom2-atom1-atom3`. Please also print the type of the bond angle (for example, `C-C-H`).

In [7]:
for i in range(natoms):
    for j in range(i):
        for k in range(j):
            if distance(lcoord[i,:],lcoord[j,:]) < 1.6 and distance(lcoord[i,:],lcoord[k,:]) < 1.6:
                print(atom_symbols[j]+"-"+atom_symbols[i]+"-"+atom_symbols[k],angle(lcoord[j,:],lcoord[i,:],lcoord[k,:]))
            if distance(lcoord[i,:],lcoord[j,:]) < 1.6 and distance(lcoord[j,:],lcoord[k,:]) < 1.6:
                print(atom_symbols[i]+"-"+atom_symbols[j]+"-"+atom_symbols[k],angle(lcoord[i,:],lcoord[j,:],lcoord[k,:]))
            if distance(lcoord[j,:],lcoord[k,:]) < 1.6 and distance(lcoord[i,:],lcoord[k,:]) < 1.6:
                print(atom_symbols[i]+"-"+atom_symbols[k]+"-"+atom_symbols[j],angle(lcoord[i,:],lcoord[k,:],lcoord[j,:]))    
                

C-C-C 120.4381098505056
C-C-C 120.43307373881382
C-C-C 120.06362313049614
C-C-C 119.92259387703254
C-C-C 120.43420602329655
C-C-C 119.07188682779349
C-C-C 120.43011621160676
C-C-C 120.0675840332504
H-C-C 109.99209093824534
H-C-C 110.89580935805935
H-C-H 108.87604443305837
H-C-C 110.89768694022479
H-C-H 108.87740131088155
H-C-H 107.22421859586296
H-C-C 120.31251246623872
H-C-C 119.25439953339851
H-C-C 119.94162355048594
H-C-C 119.99452714569934
H-C-C 120.0328676907391
H-C-C 120.04400448136244
H-C-C 119.99073693666085
H-C-C 119.94146820020558
H-C-C 120.31303394534035
H-C-C 119.2568317927332


# Calculating Spectroscopic Constants from a Potential Energy Surface 

*This lab is taken from the Psi4Education project.*

The spectroscopic constants for a diatomic molecule can be calculated from a series of potential energies computed for different bond separations.  In this lab, you will calculate the spectroscopic constants for two molecules and compare their force constants.  You will also study the effect of using the harmonic approximation in determining the vibrational energy levels.  

In [1]:
"""Calculating Spectroscopic Constants from a Potential Energy Surface"""

__authors__ = "Ashley Ringer McDonald"
__credits__ = ["Dominic A. Sirianni"]
__email__   = ["armcdona@calpoly.edu"]

__copyright__ = "(c) 2008-2019, The Psi4Education Developers"
__license__   = "BSD-3-Clause"
__date__      = "2019-11-18"

To use this lab: As you work through the lab, be sure to execute each code block.  If you don't, then when you try to write you own code, it will tell you the previous variable are undefined because the prior code blocks were not executed.

First we import the electronic structure functions into our notebook.  

In [2]:
import psi4
#import numpy as np
import matplotlib.pyplot as plt

Next contruct the molecule using the PSI4 input structure and define the values of the bond length, R.  Here we build an HF molecule.

In [3]:
mol_tmpl = """H
F 1 **R**"""
rvals = [0.8, 0.85, 0.9, 0.95, 1.0]

Each of the following `psi4.` functions calls uses the Psi4 program.  The `psi4.geometry` function creates the molecule and the `psi4.energy` function calculates the SCF/cc-pVDZ energy.

In [4]:
molecules =[]
energies = []
for r in rvals:
    molecule = psi4.geometry(mol_tmpl.replace("**R**", str(r)))
    molecules.append(molecule)
for mol in molecules:
    energy = psi4.energy("SCF/cc-pVDZ", molecule=mol)
    energies.append(energy)
print(rvals)
print(energies)


Scratch directory: /tmp/

*** tstart() called on MacBook-Pro-225.local
*** at Thu Mar 30 10:44:49 2023

   => Loading Basis Set <=

    Name: CC-PVDZ
    Role: ORBITAL
    Keyword: BASIS
    atoms 1 entry H          line    22 file /Users/konrad/opt/anaconda3/envs/class/share/psi4/basis/cc-pvdz.gbs 
    atoms 2 entry F          line   228 file /Users/konrad/opt/anaconda3/envs/class/share/psi4/basis/cc-pvdz.gbs 


         ---------------------------------------------------------
                                   SCF
               by Justin Turney, Rob Parrish, Andy Simmonett
                          and Daniel G. A. Smith
                              RHF Reference
                        1 Threads,    500 MiB Core
         ---------------------------------------------------------

  ==> Geometry <==

    Molecular point group: c2v
    Full point group: C_inf_v

    Geometry (in Angstrom), charge = 0, multiplicity = 1:

       Center              X                  Y               

             A1    A2    B1    B2 
    DOCC [     3,    0,    1,    1 ]

  @DF-RHF Final Energy:  -100.01584984980730

   => Energetics <=

    Nuclear Repulsion Energy =              5.6030528188588233
    One-Electron Energy =                -151.3724457295125774
    Two-Electron Energy =                  45.7535430608464537
    Total Energy =                       -100.0158498498072959

Computation Completed


Properties will be evaluated at   0.000000,   0.000000,   0.000000 [a0]

Properties computed using the SCF density matrix


 Multipole Moments:

 ------------------------------------------------------------------------------------
     Multipole            Electronic (a.u.)      Nuclear  (a.u.)        Total (a.u.)
 ------------------------------------------------------------------------------------

 L = 1.  Multiply by 2.5417464519 to convert [e a0] to [Debye]
 Dipole X            :          0.0000000            0.0000000            0.0000000
 Dipole Y            :          0


*** tstart() called on MacBook-Pro-225.local
*** at Thu Mar 30 10:44:49 2023

   => Loading Basis Set <=

    Name: CC-PVDZ
    Role: ORBITAL
    Keyword: BASIS
    atoms 1 entry H          line    22 file /Users/konrad/opt/anaconda3/envs/class/share/psi4/basis/cc-pvdz.gbs 
    atoms 2 entry F          line   228 file /Users/konrad/opt/anaconda3/envs/class/share/psi4/basis/cc-pvdz.gbs 


         ---------------------------------------------------------
                                   SCF
               by Justin Turney, Rob Parrish, Andy Simmonett
                          and Daniel G. A. Smith
                              RHF Reference
                        1 Threads,    500 MiB Core
         ---------------------------------------------------------

  ==> Geometry <==

    Molecular point group: c2v
    Full point group: C_inf_v

    Geometry (in Angstrom), charge = 0, multiplicity = 1:

       Center              X                  Y                   Z               Mass  

   => Loading Basis Set <=

    Name: (CC-PVDZ AUX)
    Role: JKFIT
    Keyword: DF_BASIS_SCF
    atoms 1 entry H          line    51 file /Users/konrad/opt/anaconda3/envs/class/share/psi4/basis/cc-pvdz-jkfit.gbs 
    atoms 2 entry F          line   271 file /Users/konrad/opt/anaconda3/envs/class/share/psi4/basis/cc-pvdz-jkfit.gbs 

  ==> Integral Setup <==

  DFHelper Memory: AOs need 0.000 GiB; user supplied 0.366 GiB. Using in-core AOs.

  ==> MemDFJK: Density-Fitted J/K Matrices <==

    J tasked:                   Yes
    K tasked:                   Yes
    wK tasked:                   No
    OpenMP threads:               1
    Memory [MiB]:               375
    Algorithm:                 Core
    Schwarz Cutoff:           1E-12
    Mask sparsity (%):       0.0000
    Fitting Condition:        1E-10

   => Auxiliary Basis Set <=

  Basis Set: (CC-PVDZ AUX)
    Blend: CC-PVDZ-JKFIT
    Number of shells: 33
    Number of basis functions: 93
    Number of Cartesian functions: 106
  

This makes a nicer chart:

In [ ]:
for num, r in enumerate(rvals):
    print(r, ':', energies[num])

*What is the general trend in the energy for these bond distances? Offer an explaination as to why this seems reasonable.*

Student answer box: 

Activity: *Plot the energies vs. R*.

In [ ]:
#Write you code here


The next function uses the bond distances and the energies to derive the spectroscopic constants for the molecule.  These are output to a Python dictionary which is called `data` in this example.  All of the values are given in cm$^{-1}$.

In [ ]:
data = psi4.diatomic.anharmonicity(rvals, energies)

In [ ]:
print(data)

To access an element of `data` in a later computation, you use the syntax: 

In [ ]:
data['nu']

Activity: *Calculate the energies of the n vibrational levels.  Recall that the vibrational energy levels are given by $$ E_n = \omega_e \left( n+ \frac{1}{2} \right)  - \omega_e x_e \left( n + \frac{1}{2} \right)^2   $$ where the second term is the anharmonic correction.  Assuming J=0, calculate the energy for the n=0 to n=3 energy levels, with and without the anharmonic correction.  Remember, you can access the $ \omega_e $ and $ \omega_e x_e $ values from the `data` dictionary.  Have your code print your values.*

In [ ]:
#Write your code here


Activity: *Calculate the difference between the harmonic and the anharmonic energies and print these values.*

In [ ]:
# Write your code here


*Is it more important to include anharmonicity corrections for ground state energy calculations or excited state calculations? Explain your answer.*

Write your answer here:  

Activity: *Calculate the $ \Delta E $ for n=0 to n=1 and n=1 to n=2.  Compare the results for the harmonic approximation and the anharmonic results.*

In [ ]:
# Write your code here


*Is the spacing of the energy levels equal?  Explain your answer.*  

Write your answer here: 

Activity: *Calculate the force constant for the HF bond in N/m.  $$ \omega_e = \frac{1}{2\pi c} \sqrt \frac{k}{\mu} $$  Remember that $ \mu $ is the reduced mass of HF.*

In [ ]:
# Write your code here


Activity: *Construct and plot the PES for CO.  Determine $\omega_e$, $\omega_e x_e$, $\mu$, and k for CO.  Add additional cells to your jupyter notebook as needed.* 

In [ ]:
# Write your code here:


Question: *Based on your results, is anharmonicity a more significant factor for HF or CO?*

Write your answer here:

Question: *Is the force constant greater for HF or CO?  Do your results agree with the typical bond orders expected for HF and CO?*

Write your answer here: