# CHEM7370 Class 16
## Calculating bond lengths and angles
Let's now go back to the XYZ geometry of toluene. We want to find the bond lengths present in this molecule.

At the moment, the nuclear coordinates are contained in the string variable `xyz`, so first we need to convert them into a NumPy array.

In [7]:
import numpy as np
xyz = '''15
XYZ geometry from RDKit
C 2.2126 -0.1714 0.0957
C 0.7202 -0.0520 0.0066
C 0.0966 1.1905 0.1749
C -1.2944 1.2963 0.1233
C -2.0737 0.1601 -0.0865
C -1.4630 -1.0830 -0.2404
C -0.0721 -1.1901 -0.1890
H 2.5123 -0.3511 1.1327
H 2.6995 0.7425 -0.2605
H 2.5763 -0.9961 -0.5262
H 0.6916 2.0845 0.3467
H -1.7697 2.2653 0.2497
H -3.1565 0.2429 -0.1257
H -2.0699 -1.9706 -0.3979
H 0.3903 -2.1678 -0.3034
'''
xyz_lines = xyz.split("\n")
natoms = int(xyz_lines[0])
lcoord = []
atom_symbols = []
for atom in xyz_lines[2:natoms+2]:
    atom_symbols.append(atom.split()[0])
    lcoord.append([float(x) for x in atom.split()[1:]])
lcoord = np.array(lcoord)
print(lcoord)

[[ 2.2126 -0.1714  0.0957]
 [ 0.7202 -0.052   0.0066]
 [ 0.0966  1.1905  0.1749]
 [-1.2944  1.2963  0.1233]
 [-2.0737  0.1601 -0.0865]
 [-1.463  -1.083  -0.2404]
 [-0.0721 -1.1901 -0.189 ]
 [ 2.5123 -0.3511  1.1327]
 [ 2.6995  0.7425 -0.2605]
 [ 2.5763 -0.9961 -0.5262]
 [ 0.6916  2.0845  0.3467]
 [-1.7697  2.2653  0.2497]
 [-3.1565  0.2429 -0.1257]
 [-2.0699 -1.9706 -0.3979]
 [ 0.3903 -2.1678 -0.3034]]


We will need a function that takes two `numpy` arrays `atom1` and `atom2` (each with 3 coordinates) and calculates the distance between the two atoms. Complete this function.

In [8]:
def distance(atom1,atom2):
#    return np.sqrt((atom2[0]-atom1[0])*(atom2[0]-atom1[0])+(atom2[1]-atom1[1])*(atom2[1]-atom1[1])+(
#        atom2[2]-atom1[2])*(atom2[2]-atom1[2]))
    return np.sqrt(np.sum((atom2-atom1)*(atom2-atom1)))

Let's now pick every pair of atoms (with the double `for` loop), calculate the distance, and print it if it's less than 1.6 Angstroms (so that it likely represents a bond). Complete the code inside the loops.

In [9]:
for i in range(natoms):
    for j in range(i):
        dist = distance(lcoord[i,:],lcoord[j,:])
        if dist < 1.6:
            print(dist)

1.4998176322473344
1.400359989431289
1.3959717762189894
1.3936552550756591
1.3935341079428232
1.4004535908054931
1.3959638892177693
1.0942948323006922
1.0950631306002407
1.0950650163346467
1.0875551664168581
1.0866683256633551
1.0866684498962873
1.0867233410578794
1.0875653589554977


Modify the code above so that, for every bond, it also prints the bond type (C-C or C-H). Remember that we saved the `atom_symbols` array.

In [10]:
for i in range(natoms):
    for j in range(i):
        dist = distance(lcoord[i,:],lcoord[j,:])
        if dist < 1.6:
            print(atom_symbols[i]+"-"+atom_symbols[j],dist)

C-C 1.4998176322473344
C-C 1.400359989431289
C-C 1.3959717762189894
C-C 1.3936552550756591
C-C 1.3935341079428232
C-C 1.4004535908054931
C-C 1.3959638892177693
H-C 1.0942948323006922
H-C 1.0950631306002407
H-C 1.0950650163346467
H-C 1.0875551664168581
H-C 1.0866683256633551
H-C 1.0866684498962873
H-C 1.0867233410578794
H-C 1.0875653589554977


As our last task, let's find the bond angles in this molecule.

A short refresher from geometry: the dot product `np.dot(v1,v2)` of two vectors *v<sub>1</sub>=(x<sub>1</sub>,y<sub>1</sub>,z<sub>1</sub>)* and *v<sub>2</sub>=(x<sub>2</sub>,y<sub>2</sub>,z<sub>2</sub>)* equals *x<sub>1</sub>x<sub>2</sub>+y<sub>1</sub>y<sub>2</sub>+z<sub>1</sub>z<sub>2</sub>*. This dot product is equal to the product of the lengths of *v<sub>1</sub>* and *v<sub>2</sub>* times the cosine of the angle between the two vectors. If you calculate the cosine, you can use the inverse cosine function `np.arccos()` to get the angle - just remember that this angle will be in radians, and you need to multiply it by `180.0/np.pi` to convert it to degrees.

Complete the function that takes three `numpy` arrays `atom1`, `atom2`, `atom3` (each with 3 coordinates) and calculates the `atom1-atom2-atom3` angle.

In [11]:
def angle(atom1,atom2,atom3):
    v1 = atom1 - atom2
    v2 = atom3 - atom2
    v1dotv2 = np.dot(v1,v2)
    lenv1 = distance(atom2,atom1)
    lenv2 = distance(atom3,atom2)
    cosalpha = v1dotv2/(lenv1*lenv2)
    return np.arccos(cosalpha)*180.0/np.pi

Now, use the definition of `angle` to print the angles between any two bonds sharing a common atom. Remember that for any three atoms `atom1`, `atom2`, `atom3` you need to check three possibilities - each of the three atoms can be bonded to the other two. For example, if `atom1` is bonded to both `atom2` and `atom3`, you need to print the angle `atom2-atom1-atom3`. Please also print the type of the bond angle (for example, `C-C-H`).

In [12]:
for i in range(natoms):
    for j in range(i):
        for k in range(j):
            if distance(lcoord[i,:],lcoord[j,:]) < 1.6 and distance(lcoord[i,:],lcoord[k,:]) < 1.6:
                print(atom_symbols[j]+"-"+atom_symbols[i]+"-"+atom_symbols[k],angle(lcoord[j,:],lcoord[i,:],lcoord[k,:]))
            if distance(lcoord[i,:],lcoord[j,:]) < 1.6 and distance(lcoord[j,:],lcoord[k,:]) < 1.6:
                print(atom_symbols[i]+"-"+atom_symbols[j]+"-"+atom_symbols[k],angle(lcoord[i,:],lcoord[j,:],lcoord[k,:]))
            if distance(lcoord[j,:],lcoord[k,:]) < 1.6 and distance(lcoord[i,:],lcoord[k,:]) < 1.6:
                print(atom_symbols[i]+"-"+atom_symbols[k]+"-"+atom_symbols[j],angle(lcoord[i,:],lcoord[k,:],lcoord[j,:]))    
                

C-C-C 120.43810985050564
C-C-C 120.4330737388138
C-C-C 120.06362313049614
C-C-C 119.92259387703254
C-C-C 120.43420602329655
C-C-C 119.07188682779349
C-C-C 120.43011621160676
C-C-C 120.06758403325041
H-C-C 109.99209093824534
H-C-C 110.89580935805935
H-C-H 108.87604443305837
H-C-C 110.89768694022479
H-C-H 108.87740131088155
H-C-H 107.22421859586296
H-C-C 120.31251246623873
H-C-C 119.25439953339851
H-C-C 119.94162355048594
H-C-C 119.99452714569934
H-C-C 120.0328676907391
H-C-C 120.04400448136244
H-C-C 119.99073693666085
H-C-C 119.94146820020558
H-C-C 120.31303394534035
H-C-C 119.2568317927332


Now, the specific tasks that are needed for Project 4:

In [13]:
atomic_numbers = {'H':1, 'B':5, 'C':6, 'N':7, 'O':8, 'F':9, 'P':15, 'S':16, 'Cl':17}
charges = []
for symbol in atom_symbols:
    if symbol in atomic_numbers:
        charges.append(float(atomic_numbers[symbol]))
    else:
        print ('Unknown atom:',symbol)
charges = (np.array(charges)[np.newaxis]).T
#print(charges.shape,lcoord.shape)
molecule = np.hstack((charges,lcoord))
print(molecule)
print(molecule.shape)

[[ 6.      2.2126 -0.1714  0.0957]
 [ 6.      0.7202 -0.052   0.0066]
 [ 6.      0.0966  1.1905  0.1749]
 [ 6.     -1.2944  1.2963  0.1233]
 [ 6.     -2.0737  0.1601 -0.0865]
 [ 6.     -1.463  -1.083  -0.2404]
 [ 6.     -0.0721 -1.1901 -0.189 ]
 [ 1.      2.5123 -0.3511  1.1327]
 [ 1.      2.6995  0.7425 -0.2605]
 [ 1.      2.5763 -0.9961 -0.5262]
 [ 1.      0.6916  2.0845  0.3467]
 [ 1.     -1.7697  2.2653  0.2497]
 [ 1.     -3.1565  0.2429 -0.1257]
 [ 1.     -2.0699 -1.9706 -0.3979]
 [ 1.      0.3903 -2.1678 -0.3034]]
(15, 4)


In [84]:
#task 1
# Function to read XYZ file and return atom coordinates
def read_xyz_file(filename):
    atomic_number = {
    'H': 1,
    'C': 6,
    'N': 7,
    'O': 8
}
    with open(filename, 'r') as f:
        lines = f.readlines()
        natoms = int(lines[0].strip())
        lcoords = []
        atom_symbols = []
        for line in lines[2:]:
            elements = line.strip().split()
            if len(elements) == 4:
                coords = [float(x) for x in elements[1:4]]
                atom_symbol = elements[0]
                atom_symbols.append(atom_symbol)
                lcoords.append(coords)
        atomic_numbers = np.array([atomic_number.get(atom_symbol, 0) for atom_symbol in atom_symbols])

        return np.column_stack((atomic_numbers, np.array(lcoords)))


# Read two XYZ files
file1 = "propylene_oxide1.xyz"
file2 = "water2.xyz"

#Read coordinates and atom symbols for file1
coords1 = read_xyz_file(file1)

#Read coordinates and atom symbols for file2
coords2 = read_xyz_file(file2)

print("atomic_number and Coordinates for file1:")
print(coords1)

print("atomic_number and Coordinates for file2:")
print(coords2)

FileNotFoundError: [Errno 2] No such file or directory: 'propylene_oxide1.xyz'

In [83]:
#task 2
molecule1 = coords1
molecule2 = coords2
atomic_mass = {1: 1.008, 6: 12.011, 7: 14.007, 8: 15.999}
def calculate_center_of_mass(molecule):
    symbols = molecule[:,0]
    coordinates = molecule[:,1:4]
    total_mass = 0
    center_of_mass = np.zeros([3])
    for i in range(len(symbols)):
        mass = atomic_mass[symbols[i]]
        total_mass += mass
        center_of_mass += mass *coordinates[i]
    center_of_mass /= total_mass
    return center_of_mass
print(calculate_center_of_mass(molecule1))
print(calculate_center_of_mass(molecule2))

[2.73633548 1.60201171 4.1667847 ]
[-2.92005367  2.35023928 -0.18307108]


In [77]:
#task 3

In [ ]:
#task 4

In [ ]:
#task 5
import numpy as np

molecule = np.array([   [ 6., -2.2126, 0.1714, -0.0957],
                        [ 6., -0.7202, 0.052, -0.0066],
                        [ 6., 0.7202, -0.052, 0.0066],
                        [ 6., 2.2126, -0.1714, 0.0957],
                        [ 1., -3.1417, 0.2128, -0.1192],
                        [ 1., -1.6493, 0.0934, -0.0301],
                        [ 1., -0.157, -0.0259, 0.0364],
                        [ 1., 1.3354, -0.1453, 0.1255],
                        [ 1., 2.8277, -0.2647, 0.2146],
                        [ 1., 4.3199, -0.3841, 0.3037],
                        [ 7., -0.157, -0.0259, 0.0364],
                        [ 8., 1.3354, -0.1453, 0.1255]])

# create a dictionary of atomic masses based on the atomic number
atomic_masses = {6: 12.0107, 7: 14.0067, 8: 15.9994, 1: 1.00794}

coordinates = molecule[:, 1:]

masses = np.array([atomic_masses[int(x)] for x in molecule[:, 0]])

# calculate the moment of inertia tensor
I = np.zeros((3, 3))
for i in range(len(molecule)):
    for j in range(3):
        for k in range(3):
            if j == k:
                I[j,k] += masses[i] * (coordinates[i,j]**2 + coordinates[i,k]**2)
            I[j,k] -= masses[i] * coordinates[i,j] * coordinates[i,k]

print(I)

: 

In [ ]:
#task 6

In [ ]:
#task 7

In [ ]:
#task 8

In [ ]:
#task 9

In [22]:
#task 10
def inversion(molecule):
    charges = (molecule[:,0][np.newaxis]).T
    coords = molecule[:,1:]
    inverted_coords = - coords
    inverted_molecule = np.hstack((charges,inverted_coords))
    return inverted_molecule

print(inversion(molecule))

[[ 6.     -2.2126  0.1714 -0.0957]
 [ 6.     -0.7202  0.052  -0.0066]
 [ 6.     -0.0966 -1.1905 -0.1749]
 [ 6.      1.2944 -1.2963 -0.1233]
 [ 6.      2.0737 -0.1601  0.0865]
 [ 6.      1.463   1.083   0.2404]
 [ 6.      0.0721  1.1901  0.189 ]
 [ 1.     -2.5123  0.3511 -1.1327]
 [ 1.     -2.6995 -0.7425  0.2605]
 [ 1.     -2.5763  0.9961  0.5262]
 [ 1.     -0.6916 -2.0845 -0.3467]
 [ 1.      1.7697 -2.2653 -0.2497]
 [ 1.      3.1565 -0.2429  0.1257]
 [ 1.      2.0699  1.9706  0.3979]
 [ 1.     -0.3903  2.1678  0.3034]]


In [ ]:
#tasks 999 and 1000
mol1 = read_xyz(xyz1)
mol2 = read_xyz(xyz2)
def are_these_the_same(mol1,mol2):
    com1 = center_of_mass(mol1)
    mol1a = translate(mol1,com1)
    com2 = center_of_mass(mol2)
    mol2a = translate(mol2,com2)
    axes1 = principal_axes(moment_of_inertia(mol1a))
    axes2 = principal_axes(moment_of_inertia(mol2a))
    (mol1b,axes1b) = rotate_1st_axis_to_z(mol1a,axes1)
    (mol1c,axes1c) = rotate_2nd_axis_to_y(mol1b,axes1b)
    (mol2b,axes2b) = rotate_1st_axis_to_z(mol2a,axes2)
    (mol2c,axes2c) = rotate_2nd_axis_to_y(mol2b,axes2b)
    return all_coordinates_match(mol1c,mol2c)
    
def are_these_mirror_images(mol1,mol2):
    inv_mol2 = inversion(mol2)
    return are_these_the_same(mol1,inv_mol2)