# CHEM7370 Class 16
## Calculating bond lengths and angles
Let's now go back to the XYZ geometry of toluene. We want to find the bond lengths present in this molecule.

At the moment, the nuclear coordinates are contained in the string variable `xyz`, so first we need to convert them into a NumPy array.

In [1]:
import numpy as np
xyz = '''15
XYZ geometry from RDKit
C 2.2126 -0.1714 0.0957
C 0.7202 -0.0520 0.0066
C 0.0966 1.1905 0.1749
C -1.2944 1.2963 0.1233
C -2.0737 0.1601 -0.0865
C -1.4630 -1.0830 -0.2404
C -0.0721 -1.1901 -0.1890
H 2.5123 -0.3511 1.1327
H 2.6995 0.7425 -0.2605
H 2.5763 -0.9961 -0.5262
H 0.6916 2.0845 0.3467
H -1.7697 2.2653 0.2497
H -3.1565 0.2429 -0.1257
H -2.0699 -1.9706 -0.3979
H 0.3903 -2.1678 -0.3034
'''
xyz_lines = xyz.split("\n")
natoms = int(xyz_lines[0])
lcoord = []
atom_symbols = []
for atom in xyz_lines[2:natoms+2]:
    atom_symbols.append(atom.split()[0])
    lcoord.append([float(x) for x in atom.split()[1:]])
lcoord = np.array(lcoord)
print(lcoord)

[[ 2.2126 -0.1714  0.0957]
 [ 0.7202 -0.052   0.0066]
 [ 0.0966  1.1905  0.1749]
 [-1.2944  1.2963  0.1233]
 [-2.0737  0.1601 -0.0865]
 [-1.463  -1.083  -0.2404]
 [-0.0721 -1.1901 -0.189 ]
 [ 2.5123 -0.3511  1.1327]
 [ 2.6995  0.7425 -0.2605]
 [ 2.5763 -0.9961 -0.5262]
 [ 0.6916  2.0845  0.3467]
 [-1.7697  2.2653  0.2497]
 [-3.1565  0.2429 -0.1257]
 [-2.0699 -1.9706 -0.3979]
 [ 0.3903 -2.1678 -0.3034]]


We will need a function that takes two `numpy` arrays `atom1` and `atom2` (each with 3 coordinates) and calculates the distance between the two atoms. Complete this function.

In [2]:
def distance(atom1,atom2):
#    return np.sqrt((atom2[0]-atom1[0])*(atom2[0]-atom1[0])+(atom2[1]-atom1[1])*(atom2[1]-atom1[1])+(
#        atom2[2]-atom1[2])*(atom2[2]-atom1[2]))
    return np.sqrt(np.sum((atom2-atom1)*(atom2-atom1)))

Let's now pick every pair of atoms (with the double `for` loop), calculate the distance, and print it if it's less than 1.6 Angstroms (so that it likely represents a bond). Complete the code inside the loops.

In [3]:
for i in range(natoms):
    for j in range(i):
        dist = distance(lcoord[i,:],lcoord[j,:])
        if dist < 1.6:
            print(dist)

1.4998176322473344
1.400359989431289
1.3959717762189894
1.3936552550756591
1.3935341079428232
1.4004535908054931
1.3959638892177693
1.0942948323006922
1.0950631306002407
1.0950650163346467
1.0875551664168581
1.0866683256633551
1.0866684498962873
1.0867233410578794
1.0875653589554977


Modify the code above so that, for every bond, it also prints the bond type (C-C or C-H). Remember that we saved the `atom_symbols` array.

In [4]:
for i in range(natoms):
    for j in range(i):
        dist = distance(lcoord[i,:],lcoord[j,:])
        if dist < 1.6:
            print(atom_symbols[i]+"-"+atom_symbols[j],dist)

C-C 1.4998176322473344
C-C 1.400359989431289
C-C 1.3959717762189894
C-C 1.3936552550756591
C-C 1.3935341079428232
C-C 1.4004535908054931
C-C 1.3959638892177693
H-C 1.0942948323006922
H-C 1.0950631306002407
H-C 1.0950650163346467
H-C 1.0875551664168581
H-C 1.0866683256633551
H-C 1.0866684498962873
H-C 1.0867233410578794
H-C 1.0875653589554977


As our last task, let's find the bond angles in this molecule.

A short refresher from geometry: the dot product `np.dot(v1,v2)` of two vectors *v<sub>1</sub>=(x<sub>1</sub>,y<sub>1</sub>,z<sub>1</sub>)* and *v<sub>2</sub>=(x<sub>2</sub>,y<sub>2</sub>,z<sub>2</sub>)* equals *x<sub>1</sub>x<sub>2</sub>+y<sub>1</sub>y<sub>2</sub>+z<sub>1</sub>z<sub>2</sub>*. This dot product is equal to the product of the lengths of *v<sub>1</sub>* and *v<sub>2</sub>* times the cosine of the angle between the two vectors. If you calculate the cosine, you can use the inverse cosine function `np.arccos()` to get the angle - just remember that this angle will be in radians, and you need to multiply it by `180.0/np.pi` to convert it to degrees.

Complete the function that takes three `numpy` arrays `atom1`, `atom2`, `atom3` (each with 3 coordinates) and calculates the `atom1-atom2-atom3` angle.

In [5]:
def angle(atom1,atom2,atom3):
    v1 = atom1 - atom2
    v2 = atom3 - atom2
    v1dotv2 = np.dot(v1,v2)
    lenv1 = distance(atom2,atom1)
    lenv2 = distance(atom3,atom2)
    cosalpha = v1dotv2/(lenv1*lenv2)
    return np.arccos(cosalpha)*180.0/np.pi

Now, use the definition of `angle` to print the angles between any two bonds sharing a common atom. Remember that for any three atoms `atom1`, `atom2`, `atom3` you need to check three possibilities - each of the three atoms can be bonded to the other two. For example, if `atom1` is bonded to both `atom2` and `atom3`, you need to print the angle `atom2-atom1-atom3`. Please also print the type of the bond angle (for example, `C-C-H`).

In [6]:
for i in range(natoms):
    for j in range(i):
        for k in range(j):
            if distance(lcoord[i,:],lcoord[j,:]) < 1.6 and distance(lcoord[i,:],lcoord[k,:]) < 1.6:
                print(atom_symbols[j]+"-"+atom_symbols[i]+"-"+atom_symbols[k],angle(lcoord[j,:],lcoord[i,:],lcoord[k,:]))
            if distance(lcoord[i,:],lcoord[j,:]) < 1.6 and distance(lcoord[j,:],lcoord[k,:]) < 1.6:
                print(atom_symbols[i]+"-"+atom_symbols[j]+"-"+atom_symbols[k],angle(lcoord[i,:],lcoord[j,:],lcoord[k,:]))
            if distance(lcoord[j,:],lcoord[k,:]) < 1.6 and distance(lcoord[i,:],lcoord[k,:]) < 1.6:
                print(atom_symbols[i]+"-"+atom_symbols[k]+"-"+atom_symbols[j],angle(lcoord[i,:],lcoord[k,:],lcoord[j,:]))    
                

C-C-C 120.4381098505056
C-C-C 120.43307373881382
C-C-C 120.06362313049614
C-C-C 119.92259387703254
C-C-C 120.43420602329655
C-C-C 119.07188682779349
C-C-C 120.43011621160676
C-C-C 120.0675840332504
H-C-C 109.99209093824534
H-C-C 110.89580935805935
H-C-H 108.87604443305837
H-C-C 110.89768694022479
H-C-H 108.87740131088155
H-C-H 107.22421859586296
H-C-C 120.31251246623872
H-C-C 119.25439953339851
H-C-C 119.94162355048594
H-C-C 119.99452714569934
H-C-C 120.0328676907391
H-C-C 120.04400448136244
H-C-C 119.99073693666085
H-C-C 119.94146820020558
H-C-C 120.31303394534035
H-C-C 119.2568317927332


Now, the specific tasks that are needed for Project 4:

In [7]:
atomic_numbers = {'H':1, 'B':5, 'C':6, 'N':7, 'O':8, 'F':9, 'P':15, 'S':16, 'Cl':17}
charges = []
for symbol in atom_symbols:
    if symbol in atomic_numbers:
        charges.append(float(atomic_numbers[symbol]))
    else:
        print ('Unknown atom:',symbol)
charges = (np.array(charges)[np.newaxis]).T
#print(charges.shape,lcoord.shape)
molecule = np.hstack((charges,lcoord))
print(molecule)
print(molecule.shape)

[[ 6.      2.2126 -0.1714  0.0957]
 [ 6.      0.7202 -0.052   0.0066]
 [ 6.      0.0966  1.1905  0.1749]
 [ 6.     -1.2944  1.2963  0.1233]
 [ 6.     -2.0737  0.1601 -0.0865]
 [ 6.     -1.463  -1.083  -0.2404]
 [ 6.     -0.0721 -1.1901 -0.189 ]
 [ 1.      2.5123 -0.3511  1.1327]
 [ 1.      2.6995  0.7425 -0.2605]
 [ 1.      2.5763 -0.9961 -0.5262]
 [ 1.      0.6916  2.0845  0.3467]
 [ 1.     -1.7697  2.2653  0.2497]
 [ 1.     -3.1565  0.2429 -0.1257]
 [ 1.     -2.0699 -1.9706 -0.3979]
 [ 1.      0.3903 -2.1678 -0.3034]]
(15, 4)


In [9]:
#task 1
# Function to read XYZ file and return atom coordinates
def read_xyz_file(filename):
    atomic_number = {
    'H': 1,
    'C': 6,
    'N': 7,
    'O': 8
}
    with open(filename, 'r') as f:
        lines = f.readlines()
        natoms = int(lines[0].strip())
        lcoords = []
        atom_symbols = []
        for line in lines[2:]:
            elements = line.strip().split()
            if len(elements) == 4:
                coords = [float(x) for x in elements[1:4]]
                atom_symbol = elements[0]
                atom_symbols.append(atom_symbol)
                lcoords.append(coords)
        atomic_numbers = np.array([atomic_number.get(atom_symbol, 0) for atom_symbol in atom_symbols])

        return np.column_stack((atomic_numbers, np.array(lcoords)))


# Read two XYZ files
import os
file1 = os.path.join("examples","propylene_oxide1.xyz")
file2 = os.path.join("examples","water2.xyz")

#Read coordinates and atom symbols for file1
coords1 = read_xyz_file(file1)

#Read coordinates and atom symbols for file2
coords2 = read_xyz_file(file2)

print("atomic_number and Coordinates for file1:")
print(coords1)

print("atomic_number and Coordinates for file2:")
print(coords2)

atomic_number and Coordinates for file1:
[[ 6.      -4.12149  2.41459 -0.09003]
 [ 6.      -2.67699  2.26472  0.30482]
 [ 6.      -1.65547  3.24568 -0.14713]
 [ 1.      -1.75372  3.48137 -1.21188]
 [ 1.      -0.64986  2.84752  0.02049]
 [ 1.      -1.75166  4.177    0.41938]
 [ 8.      -3.25237  1.47358 -0.74025]
 [ 1.      -4.4229   3.29025 -0.65027]
 [ 1.      -4.87872  2.01599  0.57306]
 [ 1.      -2.43764  1.78612  1.24389]]
atomic_number and Coordinates for file2:
[[8.      2.68118 1.58333 4.14362]
 [1.      3.52123 1.58333 3.65862]
 [1.      2.82687 1.91721 5.04262]]


In [10]:
#task 2
molecule1 = coords1
molecule2 = coords2
atomic_mass = {1: 1.008, 6: 12.011, 7: 14.007, 8: 15.999}

def calculate_center_of_mass(molecule):
    symbols = molecule[:,0]
    coordinates = molecule[:,1:4]
    total_mass = 0
    center_of_mass = np.zeros([3])
    for i in range(len(symbols)):
        mass = atomic_mass[symbols[i]]
        total_mass += mass
        center_of_mass += mass *coordinates[i]
    center_of_mass /= total_mass
    return center_of_mass

print(calculate_center_of_mass(molecule1))
print(calculate_center_of_mass(molecule2))

[-2.92005367  2.35023928 -0.18307108]
[2.73633548 1.60201171 4.1667847 ]


In [12]:
#task 3
def translate_molecule(molecule, shift):
    # Create the translation vector
    translation_vector = shift
    
    # Add the translation vector to the original coordinates
    translated_molecule = []
    for atom in molecule:
        atom_symbol = atom[0]
        atom_coords = np.array(atom[1:]) + translation_vector
        translated_atom = [atom_symbol] + atom_coords.tolist()
        translated_molecule.append(translated_atom)
    
    return np.array(translated_molecule)

molecule1t = translate_molecule(molecule1,-calculate_center_of_mass(molecule1))
print(molecule1t)
print(calculate_center_of_mass(molecule1t))
molecule2t = translate_molecule(molecule2,-calculate_center_of_mass(molecule2))
print(molecule2t)
print(calculate_center_of_mass(molecule2t))

[[ 6.         -1.20143633  0.06435072  0.09304108]
 [ 6.          0.24306367 -0.08551928  0.48789108]
 [ 6.          1.26458367  0.89544072  0.03594108]
 [ 1.          1.16633367  1.13113072 -1.02880892]
 [ 1.          2.27019367  0.49728072  0.20356108]
 [ 1.          1.16839367  1.82676072  0.60245108]
 [ 8.         -0.33231633 -0.87665928 -0.55717892]
 [ 1.         -1.50284633  0.94001072 -0.46719892]
 [ 1.         -1.95866633 -0.33424928  0.75613108]
 [ 1.          0.48241367 -0.56411928  1.42696108]]
[-9.17539690e-16  1.20427084e-15 -6.11693127e-17]
[[ 8.         -0.05515548 -0.01868171 -0.0231647 ]
 [ 1.          0.78489452 -0.01868171 -0.5081647 ]
 [ 1.          0.09053452  0.31519829  0.8758353 ]]
[ 1.34040249e-16 -3.08138503e-18  3.75928973e-16]


In [28]:
#task 4
#Rotating molecules around x, y and z axes

def rotate_x(molecule,angle):
    """Rotates 3-D vector around x-axis"""
    angle_radians = angle * np.pi / 180.0
    x_rotation_matrix = np.array([[1, 0, 0],
                            [0, np.cos(angle_radians), -np.sin(angle_radians)],
                            [0, np.sin(angle_radians), np.cos(angle_radians)]])
    rotated_molecule = []
    for atom in molecule:
        charge = atom[0]
        coords = atom[1:]
        rotated_coords = np.matmul(x_rotation_matrix,coords)
        rotated_atom = [charge] + rotated_coords.tolist()
        rotated_molecule.append(rotated_atom)
    
    return np.array(rotated_molecule)

def rotate_y(molecule,angle):
    """Rotates 3-D vector around y-axis"""
    angle_radians = angle * np.pi / 180.0
    y_rotation_matrix = np.array([[np.cos(angle_radians),0,np.sin(angle_radians)],
                            [0,1,0],
                            [-np.sin(angle_radians), 0, np.cos(angle_radians)]])
    rotated_molecule = []
    for atom in molecule:
        charge = atom[0]
        coords = atom[1:]
        rotated_coords = np.matmul(y_rotation_matrix,coords)
        rotated_atom = [charge] + rotated_coords.tolist()
        rotated_molecule.append(rotated_atom)
    
    return np.array(rotated_molecule)

def rotate_z(molecule,angle):
    """Rotates 3-D vector around z-axis"""
    angle_radians = angle * np.pi / 180.0
    z_rotation_matrix = np.array([[np.cos(angle_radians), -np.sin(angle_radians),0],
                            [np.sin(angle_radians), np.cos(angle_radians),0],
                            [0, 0, 1]])
    rotated_molecule = []
    for atom in molecule:
        charge = atom[0]
        coords = atom[1:]
        rotated_coords = np.matmul(z_rotation_matrix,coords)
        rotated_atom = [charge] + rotated_coords.tolist()
        rotated_molecule.append(rotated_atom)
    
    return np.array(rotated_molecule)

test = rotate_x(molecule1t,90.0)
print("Before rotation")
print(molecule1t)
print("After rotation")
print(test)
test2 = rotate_y(test,90.0)
print("After 2nd rotation")
print(test2)
test3 = rotate_z(test2,180.0)
print("After 3rd rotation")
print(test3)

Before rotation
[[ 6.         -1.20143633  0.06435072  0.09304108]
 [ 6.          0.24306367 -0.08551928  0.48789108]
 [ 6.          1.26458367  0.89544072  0.03594108]
 [ 1.          1.16633367  1.13113072 -1.02880892]
 [ 1.          2.27019367  0.49728072  0.20356108]
 [ 1.          1.16839367  1.82676072  0.60245108]
 [ 8.         -0.33231633 -0.87665928 -0.55717892]
 [ 1.         -1.50284633  0.94001072 -0.46719892]
 [ 1.         -1.95866633 -0.33424928  0.75613108]
 [ 1.          0.48241367 -0.56411928  1.42696108]]
After rotation
[[ 6.         -1.20143633 -0.09304108  0.06435072]
 [ 6.          0.24306367 -0.48789108 -0.08551928]
 [ 6.          1.26458367 -0.03594108  0.89544072]
 [ 1.          1.16633367  1.02880892  1.13113072]
 [ 1.          2.27019367 -0.20356108  0.49728072]
 [ 1.          1.16839367 -0.60245108  1.82676072]
 [ 8.         -0.33231633  0.55717892 -0.87665928]
 [ 1.         -1.50284633  0.46719892  0.94001072]
 [ 1.         -1.95866633 -0.75613108 -0.33424928]

In [22]:
#task 5
def moment_of_inertia(molecule):
# create a dictionary of atomic masses based on the atomic number
    atomic_masses = {6: 12.0107, 7: 14.0067, 8: 15.9994, 1: 1.00794}

    coordinates = molecule[:, 1:]

    masses = np.array([atomic_masses[int(x)] for x in molecule[:, 0]])

# calculate the moment of inertia tensor
    I = np.zeros((3, 3))
    for i in range(len(molecule)):
        for j in range(3):
            for k in range(3):
                if j == k:
                    I[j,j] += masses[i] * (coordinates[i,0]**2 + coordinates[i,1]**2 + coordinates[i,2]**2)
                    I[j,j] -= masses[i] * coordinates[i,j]**2
                else:
                    I[j,k] -= masses[i] * coordinates[i,j] * coordinates[i,k]

    return I

print(moment_of_inertia(test))

[[ 40.55897807   3.46468256 -20.66389398]
 [  3.46468256  81.63057457   6.30189719]
 [-20.66389398   6.30189719  65.60877328]]


In [25]:
#task 6
def principal_axes(I):
    w,v = np.linalg.eig(I)
    return (w,v)

eigenvalues,eigenvectors = principal_axes(moment_of_inertia(test))
print("Eigenvalues")
print(eigenvalues)
print("Eigenvectors")
print(eigenvectors)
print(np.matmul(moment_of_inertia(test),eigenvectors[:,0]),eigenvalues[0]*eigenvectors[:,0])

Eigenvalues
[28.21737262 75.24839626 84.33255703]
Eigenvectors
[[-0.86122437  0.48677944 -0.14607655]
 [ 0.11429037  0.46556392  0.87760352]
 [-0.49520732 -0.7391184   0.4565892 ]]
[-24.30148905   3.22497399 -13.97344947] [-24.30148905   3.22497399 -13.97344947]


In [ ]:
#task 7

In [ ]:
#task 8

In [ ]:
#task 9
    
import numpy as np

def all_coordinates_match(molecule1, molecule2, tol=1e-6):
    # Check if the number of atoms is the same
    if molecule1.shape[0] != molecule2.shape[0]:
        return False
    
    # Check if all coordinates match within the given tolerance of 0.000001
    if np.allclose(molecule1[:, 1:], molecule2[:, 1:], rtol=tol, atol=tol):
        return True
    else:
        return False

if all_coordinates_match(molecule1, molecule2):
    print("The two molecules have the same geometry (all coordinates match).")
else:
    print("The two molecules have different geometries.")


In [ ]:
#task 10
def inversion(molecule):
    charges = (molecule[:,0][np.newaxis]).T
    coords = molecule[:,1:]
    inverted_coords = - coords
    inverted_molecule = np.hstack((charges,inverted_coords))
    return inverted_molecule

print(inversion(molecule))

In [ ]:
#tasks 999 and 1000
mol1 = read_xyz(xyz1)
mol2 = read_xyz(xyz2)
def are_these_the_same(mol1,mol2):
    com1 = center_of_mass(mol1)
    mol1a = translate(mol1,com1)
    com2 = center_of_mass(mol2)
    mol2a = translate(mol2,com2)
    axes1 = principal_axes(moment_of_inertia(mol1a))
    axes2 = principal_axes(moment_of_inertia(mol2a))
    (mol1b,axes1b) = rotate_1st_axis_to_z(mol1a,axes1)
    (mol1c,axes1c) = rotate_2nd_axis_to_y(mol1b,axes1b)
    (mol2b,axes2b) = rotate_1st_axis_to_z(mol2a,axes2)
    (mol2c,axes2c) = rotate_2nd_axis_to_y(mol2b,axes2b)
    return all_coordinates_match(mol1c,mol2c)
    
def are_these_mirror_images(mol1,mol2):
    inv_mol2 = inversion(mol2)
    return are_these_the_same(mol1,inv_mol2)